<?php

namespace Database\Seeders;

use App\Models\Nilai;
use Illuminate\Database\Seeder;

class NilaiSeeder extends Seeder
{
    public function run(): void
    {
        Nilai::truncate();

        Nilai::insert([
            ['id' => 1, 'value' => 'Adaptif', 'implementasi' => 'Kreatif & inovatif', 'skor' => 10],
            ['id' => 2, 'value' => 'Adaptif', 'implementasi' => 'Siap menghadapi perubahan', 'skor' => 10],
            ['id' => 3, 'value' => 'Adaptif', 'implementasi' => 'Siap menghadapi ketidakpastian', 'skor' => 10],
            ['id' => 4, 'value' => 'Adaptif', 'implementasi' => 'Antusias dalam bekerja', 'skor' => 10],
            ['id' => 5, 'value' => 'Adaptif', 'implementasi' => 'Berinisatif (proaktif)', 'skor' => 10],
            ['id' => 40, 'value' => 'Adaptif', 'implementasi' => 'Cepat menguasai aplikasi', 'skor' => 0],
            ['id' => 41, 'value' => 'Adaptif', 'implementasi' => 'Mengamati tren baru', 'skor' => 0],
            ['id' => 42, 'value' => 'Adaptif', 'implementasi' => 'Memiliki banyak sertifikat pelatihan', 'skor' => 0],
            ['id' => 43, 'value' => 'Adaptif', 'implementasi' => 'Mengikuti arahan pimpinan', 'skor' => 0],
            ['id' => 44, 'value' => 'Adaptif', 'implementasi' => 'Mengamati tren baru', 'skor' => 0],
            ['id' => 45, 'value' => 'Adaptif', 'implementasi' => 'Berubah jika disuruh', 'skor' => 0],
            ['id' => 85, 'value' => 'Adaptif', 'implementasi' => 'Menolak sistem baru yang belum teruji', 'skor' => -10],
            ['id' => 86, 'value' => 'Adaptif', 'implementasi' => 'Siap ditugaskan apa saja', 'skor' => 0],
            ['id' => 87, 'value' => 'Adaptif', 'implementasi' => 'Bertahan cara lama', 'skor' => -10],
            ['id' => 88, 'value' => 'Adaptif', 'implementasi' => 'Menggunakan metode lama selama masih diperbolehkan', 'skor' => 0],

            ['id' => 6, 'value' => 'Akuntabel', 'implementasi' => 'Integritas', 'skor' => 10],
            ['id' => 7, 'value' => 'Akuntabel', 'implementasi' => 'Bertanggung jawab', 'skor' => 10],
            ['id' => 8, 'value' => 'Akuntabel', 'implementasi' => 'Cermat', 'skor' => 10],
            ['id' => 9, 'value' => 'Akuntabel', 'implementasi' => 'Disiplin', 'skor' => 10],
            ['id' => 10, 'value' => 'Akuntabel', 'implementasi' => 'Efektif dan efisien dalam bekerja', 'skor' => 10],
            ['id' => 11, 'value' => 'Akuntabel', 'implementasi' => 'Jujur', 'skor' => 10],
            ['id' => 46, 'value' => 'Akuntabel', 'implementasi' => 'Mendapat kejelasan', 'skor' => 0],
            ['id' => 47, 'value' => 'Akuntabel', 'implementasi' => 'Lembur', 'skor' => 0],
            ['id' => 48, 'value' => 'Akuntabel', 'implementasi' => 'Menyelesaikan perselisihan', 'skor' => 0],
            ['id' => 49, 'value' => 'Akuntabel', 'implementasi' => 'Mengambil bagian dalam tanggung jawab sosial', 'skor' => 0],
            ['id' => 50, 'value' => 'Akuntabel', 'implementasi' => 'Berorientasi pada pencapaian realisasi pekerjaan', 'skor' => 0],
            ['id' => 51, 'value' => 'Akuntabel', 'implementasi' => 'Beretika', 'skor' => 0],
            ['id' => 52, 'value' => 'Akuntabel', 'implementasi' => 'Birokratis', 'skor' => 0],
            ['id' => 53, 'value' => 'Akuntabel', 'implementasi' => 'Berkontribusi', 'skor' => 0],
            ['id' => 89, 'value' => 'Akuntabel', 'implementasi' => 'Terjadi konflik kepentingan', 'skor' => -10],

            ['id' => 12, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Berorientasi pada kepuasan stakeholder BPS', 'skor' => 10],
            ['id' => 13, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Dapat diandalkan', 'skor' => 10],
            ['id' => 14, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Melakukan perbaikan yang berkelanjutan', 'skor' => 10],
            ['id' => 15, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Melayani sepenuh hati', 'skor' => 10],
            ['id' => 16, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Ramah dalam memberikan pelayanan', 'skor' => 10],
            ['id' => 17, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Solutif', 'skor' => 10],
            ['id' => 54, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Melayani sesuai SOP', 'skor' => 0],
            ['id' => 55, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Memberikan bantuan jika diminta', 'skor' => 0],
            ['id' => 56, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Kerja sesuai jam', 'skor' => 0],
            ['id' => 57, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Menjawab seperlunya saja', 'skor' => 0],
            ['id' => 58, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Mengikuti instruksi atasan', 'skor' => 0],
            ['id' => 90, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Menggunakan aplikasi pelayanan', 'skor' => 0],
            ['id' => 91, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Memberikan informasi yang dimiliki', 'skor' => 0],
            ['id' => 92, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Mengabaikan keluhan atau masukan', 'skor' => -10],
            ['id' => 93, 'value' => 'Berorientasi Pelayanan', 'implementasi' => 'Melakukan diskriminasi', 'skor' => -10],

            ['id' => 18, 'value' => 'Harmonis', 'implementasi' => 'Saling peduli', 'skor' => 10],
            ['id' => 19, 'value' => 'Harmonis', 'implementasi' => 'Saling menghargai', 'skor' => 10],
            ['id' => 20, 'value' => 'Harmonis', 'implementasi' => 'Saling menolong', 'skor' => 10],
            ['id' => 21, 'value' => 'Harmonis', 'implementasi' => 'Bersikap positif', 'skor' => 10],
            ['id' => 22, 'value' => 'Harmonis', 'implementasi' => 'Bertoleransi', 'skor' => 10],
            ['id' => 23, 'value' => 'Harmonis', 'implementasi' => 'Merangkul keberagaman', 'skor' => 10],
            ['id' => 59, 'value' => 'Harmonis', 'implementasi' => 'Bicara seperlunya', 'skor' => 0],
            ['id' => 60, 'value' => 'Harmonis', 'implementasi' => 'Menghadiri acara kekeluargaan', 'skor' => 0],
            ['id' => 61, 'value' => 'Harmonis', 'implementasi' => 'Menghindari konflik', 'skor' => 0],
            ['id' => 62, 'value' => 'Harmonis', 'implementasi' => 'Duduk tenang di ruangan', 'skor' => 0],
            ['id' => 63, 'value' => 'Harmonis', 'implementasi' => 'Mengikuti arus kerja', 'skor' => 0],
            ['id' => 94, 'value' => 'Harmonis', 'implementasi' => 'Tidak mendebat', 'skor' => 0],
            ['id' => 95, 'value' => 'Harmonis', 'implementasi' => 'Menjaga rahasia rekan', 'skor' => 0],
            ['id' => 96, 'value' => 'Harmonis', 'implementasi' => 'Menghindari kerja sama', 'skor' => -10],
            ['id' => 97, 'value' => 'Harmonis', 'implementasi' => 'Memicu pertengkaran', 'skor' => -10],

            ['id' => 24, 'value' => 'Kolaboratif', 'implementasi' => 'Terbuka dalam komunikasi', 'skor' => 10],
            ['id' => 25, 'value' => 'Kolaboratif', 'implementasi' => 'Bekerja sama', 'skor' => 10],
            ['id' => 26, 'value' => 'Kolaboratif', 'implementasi' => 'Mengelola sumber daya untuk tujuan bersama', 'skor' => 10],
            ['id' => 27, 'value' => 'Kolaboratif', 'implementasi' => 'Berperilaku adil', 'skor' => 10],
            ['id' => 28, 'value' => 'Kolaboratif', 'implementasi' => 'Memberdayakan pegawai (empowering)', 'skor' => 10],
            ['id' => 29, 'value' => 'Kolaboratif', 'implementasi' => 'Kolaborasi antar tim kerja', 'skor' => 10],
            ['id' => 64, 'value' => 'Kolaboratif', 'implementasi' => 'Hadir rapat koordinasi', 'skor' => 0],
            ['id' => 65, 'value' => 'Kolaboratif', 'implementasi' => 'Menerima semua pekerjaan', 'skor' => 0],
            ['id' => 66, 'value' => 'Kolaboratif', 'implementasi' => 'Ikut keputusan kelompok', 'skor' => 0],
            ['id' => 67, 'value' => 'Kolaboratif', 'implementasi' => 'Kerjakan tugas sesuai porsi', 'skor' => 0],
            ['id' => 68, 'value' => 'Kolaboratif', 'implementasi' => 'Menerima bantuan rekan kerja', 'skor' => 0],
            ['id' => 69, 'value' => 'Kolaboratif', 'implementasi' => 'Libatkan banyak pihak', 'skor' => 0],
            ['id' => 98, 'value' => 'Kolaboratif', 'implementasi' => 'Menghargai pekerjaan orang lain', 'skor' => 0],
            ['id' => 99, 'value' => 'Kolaboratif', 'implementasi' => 'Sembunyikan data tim', 'skor' => -10],
            ['id' => 100, 'value' => 'Kolaboratif', 'implementasi' => 'Klaim karya orang', 'skor' => -10],

            ['id' => 30, 'value' => 'Kompeten', 'implementasi' => 'Senang belajar', 'skor' => 10],
            ['id' => 31, 'value' => 'Kompeten', 'implementasi' => 'Memberikan kinerja terbaik', 'skor' => 10],
            ['id' => 32, 'value' => 'Kompeten', 'implementasi' => 'Menjaga kualitas', 'skor' => 10],
            ['id' => 33, 'value' => 'Kompeten', 'implementasi' => 'Bersikap profesional', 'skor' => 10],
            ['id' => 34, 'value' => 'Kompeten', 'implementasi' => 'Knowledge sharing (berbagi pengetahuan)', 'skor' => 10],
            ['id' => 70, 'value' => 'Kompeten', 'implementasi' => 'Produktif', 'skor' => 0],
            ['id' => 71, 'value' => 'Kompeten', 'implementasi' => 'Konsisten', 'skor' => 0],
            ['id' => 72, 'value' => 'Kompeten', 'implementasi' => 'Berorientasi jangka panjang', 'skor' => 0],
            ['id' => 73, 'value' => 'Kompeten', 'implementasi' => 'Berorientasi pada pencapaian realisasi pekerjaan', 'skor' => 0],
            ['id' => 74, 'value' => 'Kompeten', 'implementasi' => 'Kompetitif', 'skor' => 0],
            ['id' => 75, 'value' => 'Kompeten', 'implementasi' => 'Berkontribusi', 'skor' => 0],
            ['id' => 76, 'value' => 'Kompeten', 'implementasi' => 'Berpikir menyeluruh', 'skor' => 0],
            ['id' => 77, 'value' => 'Kompeten', 'implementasi' => 'Bekerja sesuai kebiasaan lama tanpa evaluasi', 'skor' => -10],
            ['id' => 78, 'value' => 'Kompeten', 'implementasi' => 'Berprestasi', 'skor' => 0],
            ['id' => 79, 'value' => 'Kompeten', 'implementasi' => 'Menghindari tugas di luar bidang utama', 'skor' => -10],

            ['id' => 35, 'value' => 'Loyal', 'implementasi' => 'Menjaga nama baik instansi dan negara', 'skor' => 10],
            ['id' => 36, 'value' => 'Loyal', 'implementasi' => 'Selalu memegang teguh ideologi Pancasila & UUD 45', 'skor' => 10],
            ['id' => 37, 'value' => 'Loyal', 'implementasi' => 'Menaati aturan/kebijakan', 'skor' => 10],
            ['id' => 38, 'value' => 'Loyal', 'implementasi' => 'Menjaga rahasia jabatan dan negara', 'skor' => 10],
            ['id' => 39, 'value' => 'Loyal', 'implementasi' => 'Berdedikasi', 'skor' => 10],
            ['id' => 80, 'value' => 'Loyal', 'implementasi' => 'Pulang tepat waktu', 'skor' => 0],
            ['id' => 81, 'value' => 'Loyal', 'implementasi' => 'Menggunakan seragam dinas', 'skor' => 0],
            ['id' => 82, 'value' => 'Loyal', 'implementasi' => 'Mengisi absensi harian', 'skor' => 0],
            ['id' => 83, 'value' => 'Loyal', 'implementasi' => 'Menyelesaikan tugas rutin', 'skor' => 0],
            ['id' => 84, 'value' => 'Loyal', 'implementasi' => 'Ikut upacara', 'skor' => 0],
            ['id' => 101, 'value' => 'Loyal', 'implementasi' => 'Mengikuti briefing harian', 'skor' => 0],
            ['id' => 102, 'value' => 'Loyal', 'implementasi' => 'Memakai tanda pengenal', 'skor' => 0],
            ['id' => 103, 'value' => 'Loyal', 'implementasi' => 'Bekerja hingga lembur', 'skor' => 0],
            ['id' => 104, 'value' => 'Loyal', 'implementasi' => 'Tidak pernah mengkritik', 'skor' => -10],
            ['id' => 105, 'value' => 'Loyal', 'implementasi' => 'Utamakan bisnis pribadi', 'skor' => -10],

            ['id' => 106, 'value' => 'Uji Coba', 'implementasi' => 'Membantu rekan kerja', 'skor' => 10],
            ['id' => 107, 'value' => 'Uji Coba', 'implementasi' => 'Memberikan masukan', 'skor' => 10],
            ['id' => 108, 'value' => 'Uji Coba', 'implementasi' => 'Menyelesaikan laporan', 'skor' => 10],
            ['id' => 109, 'value' => 'Uji Coba', 'implementasi' => 'Melayani responden', 'skor' => 10],
            ['id' => 110, 'value' => 'Uji Coba', 'implementasi' => 'Berbagi pengetahuan', 'skor' => 10],
            ['id' => 111, 'value' => 'Uji Coba', 'implementasi' => 'Mengikuti rapat', 'skor' => 0],
            ['id' => 112, 'value' => 'Uji Coba', 'implementasi' => 'Mengisi presensi', 'skor' => 0],
            ['id' => 113, 'value' => 'Uji Coba', 'implementasi' => 'Membalas email', 'skor' => 0],
            ['id' => 114, 'value' => 'Uji Coba', 'implementasi' => 'Menata arsip', 'skor' => 0],
            ['id' => 115, 'value' => 'Uji Coba', 'implementasi' => 'Istirahat siang', 'skor' => 0],
            ['id' => 116, 'value' => 'Uji Coba', 'implementasi' => 'Datang terlambat', 'skor' => -10],
            ['id' => 117, 'value' => 'Uji Coba', 'implementasi' => 'Mengabaikan pesan', 'skor' => -10],
            ['id' => 118, 'value' => 'Uji Coba', 'implementasi' => 'Menunda pekerjaan', 'skor' => -10],
            ['id' => 119, 'value' => 'Uji Coba', 'implementasi' => 'Pulang sebelum waktunya', 'skor' => -10],
            ['id' => 120, 'value' => 'Uji Coba', 'implementasi' => 'Tidak hadir rapat', 'skor' => -10],
        ]);
    }
}